server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weibo?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl